### PR TITLE
Adding IP address to the interface 

### PR DESCRIPTION
**Pull request by felixfaisal**
The struct used for `sw_interface_add_del_address` 
```rust 
pub struct SWInterfaceAddDelAddress {
    pub client_index: u32,
    pub context: u32,
    pub sw_if_index: InterfaceIndex,
    pub is_add: bool,
    pub del_all: bool,
    pub prefix: Prefix,
}
type InterfaceIndex = u32;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Prefix {
    pub address: Address,
    pub len: u8,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Address {
    pub af: AddressFamily,
    pub un: AddressUnion,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AddressFamily {
    ADDRESS_IP4 = 0,
    ADDRESS_IP6 = 1,
}
// #[derive(Debug, Clone, Serialize, Deserialize)]
/* pub struct AddressUnion {
    IP4: [u8; 4],
}*/
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AddressUnion{
    IP4([u8;4]), 
    IP6([u8;16]),
}```
// Note: Using Enum here for Unions 
// implementation/sending message
    let create_interface_reply: SWInterfaceAddDelAddressReply = send_recv_msg(
        "sw_interface_add_del_address_5803d5c4",
        &SWInterfaceAddDelAddress {
            client_index: t.get_client_index(),
            context: 0,
            sw_if_index: 0,
            is_add: true,
            del_all: false,
            prefix: 
                        Prefix{
                            address: Address {
                                    af: AddressFamily::ADDRESS_IP4,
                                    un: AddressUnion::IP4([10,10,0,2]),
                            },
                            len: 20,
                      }
                    
        },
        &mut *t,
        "sw_interface_add_del_address_reply_e8d4e804"
    );
    // 10.10.1.2/24
    println!("Create Interface Reply: {:#?}", &create_interface_reply);
 ```

 ### Output 
 
image
This is when you try to assign an IP Address to local0 which has an Idx 0, It should be showing retval code for something like operation not permitted or something because local0 doesn't allow adding ip addresses 

I then create a new host interface 
image
Modify the above, request to have Idx 2 and IP address 10.10.1.2/24

I get the following output 
image
A -59 retval code and no ip address has been assigned 

image

## Problems 
Changing the union structure doesn't change the bincode I believe, this is an implementation of using AddressUnion as an Enum

### CODE REVIEW

**Comment by ayourtch** [comment]
Right so this is a very nice puzzle here, which I think is a great troubleshooting exercise, so I will leave you the tomorrow to try and crack it yourself, if you get stuck we go through the process on Friday :-)

Few starting points: 

1) On the minus side, VPP does not like the message. On the plus side, this is about the most debug-friendly manifestation of this kind of problem, so we are in luck since debugging is possible just by studying the code, and the dumps that you have grabbed, thanks for that! :)

2) The errno of -59, which you can look up in src/vnet/api_errno.h, is VNET_API_ERROR_ADDRESS_LENGTH_MISMATCH.

Debugging approaches:

A) "code reader":

1) You can use the C source code to trace the codepath and see what issue with the message causes this error - you know the message handler function, you know where the error is thrown, 

2) Then you can stare at the message side by side with the .api file definitions that correspond to it, and try to map the binary data to the .api fields to see what the values should be, and go from there.

B) "gdb-at man":

1) fire up VPP in gdb, put the breakpoint on where this error message is being returned. (ping me if you have any Q about gdb or how to run VPP under gdb)

2) run the client program

3) VPP will drop into gdb on breakpoint

4) within GDB, analyze the arguments and variables which is being passed to the functions, and whether their values are what you expect them to be, and if not, try to figure out why.

5) Then you can stare at the values vs. the api file vs. what you are setting them to on the client side, and see what is going on.

**Comment by felixfaisal** [comment]
So here's what i did  
**Unions** are supposed to have the size of the largest field, even if the current field is an IP4 address, it should have a length of 16 ,with only first 4 representing the IP4 address, that is why we were getting `errno ~59` 

So I changed the array to be of 16 len, but the problem doesn't end there, the right IP address wasn't getting assigned so I checked the bincode to realize that there were additional 0s added when ever the field type was a structt and inside that there was an enum so totally I would have 3 0s. 

So I used an even hackier approach 
```rust 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SWInterfaceAddDelAddress {
    pub client_index: u32,
    pub context: u32,
    pub sw_if_index: InterfaceIndex,
    pub is_add: bool,
    pub del_all: bool,
    pub af: u8, 
    pub un: [u8;16], 
    pub len: u8
}
``` 

Implementation: 
```rust 
    let create_interface_reply: SWInterfaceAddDelAddressReply = send_recv_msg(
        "sw_interface_add_del_address_5803d5c4",
        &SWInterfaceAddDelAddress {
            client_index: t.get_client_index(),
            context: 0,
            sw_if_index: 1,
            is_add: true,
            del_all: false,
            af: 0, 
            un: [0xa,0xa,1,2,7,0x7a,0xb,0xc,0xd,0xf,8,9,5,6,10,10], 
            len: 24         
        },
        &mut *t,
        "sw_interface_add_del_address_reply_e8d4e804"
    ); 
``` 
    And for the following code the output is 
    
image

VPP checking IP 

image

## Key Take Aways 
1. Encoding the entire message has problems if it has multiple nest structures underneath because of which you get additional 0s here and their which would change your message 
2. We can use Unions as Enums, as long as all the fields are the size of the max field of the union 
3. We need to have associated methods for enums, and structs and unions to encode them into bincode 
4. By doing this, I think we have probably tackled the problem of a union 

Lastly, I didn't get to use gdb much as i just rethought of unions and changed the messages, It'd be great if we still talked about gdb during Friday's meet as I'll need to do that pretty soon.

**Comment by ayourtch** [comment]
Surely, we still will talk about gdb - though I think it might be worth it to dig into the question of why the extra zeroes are being added. simply flattening the data structure is possible, but that would give up any advantage that we might have from Rust's strong type system - so we ought to figure out a better approach... Let's discuss more tomorrow.

**Comment by felixfaisal** [comment]
Yep, So i digged a little deeper into what was causing it, Here is how the message should look like and what it is apparently showing 
image

So as you see the Address Family needs to be encoded as u8 instead of u32, because of which there are additional zeroes
As the encoder has fixint encoding option, it will encode all enum determinants as u32 
image

**Comment by ayourtch** [comment]
Right, so one way to deal with this is to use wrapper types, my approach was as follows:  https://github.com/ayourtch/vpp-api-encoding/blob/main/src/typ.rs#L319

**Comment by ayourtch** [comment]
it was aimed for simple enums - but maybe it can be adapted for the variant types as well…

**Pull request merged**
